[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["RaskoeStud <rasm546d@stud.kea.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.92.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
